version: '3'
services:
  jupyter-knowrob:
    image: jupyter-knowrob:master
    build:
      context: ../
      dockerfile: ./binder/Dockerfile
    stdin_open: true
    tty: true
    ports: 
      - 8888:8888
      # - 11311:11311
    privileged: true
    # user: root
    user: "jovyan:${GID}"
    working_dir: /home/jovyan/
    command: jupyter lab --allow-root --NotebookApp.token='' --no-browser --ip=0.0.0.0
    volumes:
      - ../:/home/jovyan/jupyter-knowrob